name: release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Test
        run: cargo test
