name: release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: debug
        shell: cmd
        run: |
          where gh
          gh auth token
      # - name: Test
      #   run: cargo test
      # - name: Build
      #   run: |
      #     rustup toolchain list
      #     cargo build --release --locked
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ runner.os }}-gh-ghes-webhook
      #     path: target/release/gh-ghes-webhook
